### PR TITLE
Update rage.js to ignore throwing weapons

### PR DESCRIPTION
**Pull request by shawndibble**
May want to turn on ignore whitespace changes.
Thanks to Norc#5108 for this latest version

### CODE REVIEW

**Comment by Norc** [comment]
Awesome, thanks. I just got around to trying my hand at my own pull request, so I'm going to (try to) do one myself also. The only difference between the version in this pull request and the one I'm going to try to do is I cleaned up the whitespace on my latest one by purging all unnecessary spaces in favor of tabs. Thanks!!

**Comment by Norc** [comment]
The new version also does a lot more than ignore throwing weapons. It's basically a version 2.0 this is my summary of changes:

Essentially version 2.0 Has important bug fixes for rage damage and rage damage resistances. Also  restores and fixes Rage resource consumption. New  features include better support for thrown weapons,  support for non-Strength based barbarians, and an optional rage macro icon and name toggle.

**Comment by AnthonyVadala** [comment]
Closing since #63 contains these fixes and more

**Comment by shawndibble** [comment]
#63 has no file changes

**Pull request closed without merging**
